### ISSUE TITLE
Change default branch to gh-pages

### ISSUE THREAD

**Issue by bnjbvr** [PeterJensen/mandelbrot#14]
Happy new year @PeterJensen!

Would it be possible to change the default branch to gh-pages please, so that we don't need to merge from master to gh-pages all the time, nor forget to do so?

Here's the github documentation, just in case: https://help.github.com/articles/setting-the-default-branch/

Cheers!

**Comment by PeterJensen** [comment]
Happy New Year to you as well @bnjbvr 

I made gh-pages the default branch.

Excellent suggestion.  I've found this rather tedious as well.  Of course, now we have to remember to merge the changes into the master branch as well :)

**Comment by bnjbvr** [comment]
Nice, thank you! I've done that for a few projects of mine; in fact, you can even delete the `master` branch, once it's not the default branch anymore. In this case, no need to worry about merges at all!
